<template>
  <div
    class="relative"
    :class="canvasCursorClass"

    @mousedown="startDrawing"
    @mousemove="draw"
    @mouseup="stopDrawing"

    @touchstart="startDrawing"
    @touchmove.prevent="draw"
    @touchend="stopDrawing"
  >
    <img
      ref="imageRef"
      :src="imageSrc"
      class="object-contain select-none"
      :style="{ maxHeight: `${maxHeight}px`, maxWidth: `${maxWidth}px`}"

      @load="onImageLoad"
      @dragstart.prevent
      @contextmenu="(event) => event.preventDefault()"
    />
    <div
      v-if="!isHintCollapsed"
      class="absolute top-2.5 left-2.5 right-2.5 z-10 sm:right-auto"
    >
      <div
        class="max-w-xs overflow-hidden rounded-xl border border-white/15 bg-stone-950/55 text-white shadow-lg backdrop-blur-md"
      >
        <div class="flex items-center justify-between gap-2 border-b border-white/10 px-2.5 py-1.5">
          <div class="flex items-center gap-1.5 min-w-0">
            <span
              class="rounded-full px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-[0.14em]"
              :class="hintBadgeClass"
            >
              {{ hintBadgeLabel }}
            </span>
            <span class="truncate text-[11px] text-white/65">Help</span>
          </div>
        </div>
        <p class="px-2.5 py-2 text-xs leading-4.5 text-white/90">
          {{ interactionHint }}
        </p>
      </div>
    </div>
    <svg
      class="absolute top-0 left-0 pointer-events-none"
      xmlns="http://www.w3.org/2000/svg"
      :width="imageSize.width"
      :height="imageSize.height"
    >
      <template v-if="!hideContours">
        <template v-for="contourItem in displayContours" :key="contourItem.key">
          <polygon
            :points="getReactiveSvgPoints(contourItem.contour)"
            :fill="getPolygonFillColor(contourItem.labelId, contourItem.contourIndex, contourItem.color)"
            :stroke="getPolygonStrokeColor(contourItem.labelId, contourItem.contourIndex, contourItem.color)"
            :stroke-width="getPolygonStrokeWidth(contourItem.labelId, contourItem.contourIndex)"
            fill-rule="evenodd"
            class="pointer-events-auto"
            @click.left.stop="contourItem.selectable && maybeActivateLabel(contourItem.labelId)"
            @touchend.stop.prevent="contourItem.selectable && maybeActivateLabel(contourItem.labelId)"
            @mouseenter="contourItem.isActive && setHoveredPolygon(contourItem.labelId, contourItem.contourIndex)"
            @mouseleave="contourItem.isActive && clearHoveredPolygon(contourItem.labelId, contourItem.contourIndex)"
          />
        </template>
      </template>
      <polyline
        v-if="drawing && currentContour.length"
        :points="getReactiveSvgPoints(currentContour)"
        fill="none"
        :stroke="props.activeLabel ? props.labels.find(label => label.id === props.activeLabel)?.color : '#000000'"
        stroke-width="2"
      />
      <polyline
        :points="getReactiveCropPoints(currentCrop)"
        fill="none"
        stroke="#33EECC"
        stroke-width="2"
        stroke-dasharray="5,3"
      />
    </svg>
  </div>
</template>

<script lang="ts" setup>
import { ref, computed, nextTick, watch, onMounted, onBeforeUnmount, toRef } from 'vue';
import type { LabelItem, DataLabel } from '@/api';
import { AIBackendCalls } from '@/api'
import { useDataStore } from '@/stores/data';
import { useUserStore } from '@/stores/user'
import { useImageLabelerInteraction, type CropDraft, type CropRect, type Point } from '@/composables/useImageLabelerInteraction';

// TODO: maybe include the whole data label object instead of just items to the props
const props = defineProps<{
  imageSrc: string;
  maxHeight: number;
  maxWidth: number;
  labels: LabelItem[];
  crop: CropRect | null; // [x, y, width, height] in normalized coordinates [0,1]
  activeLabel: string | null;
  hideContours: boolean;
}>();

const emit = defineEmits<{
  (e: 'update:labels', value: LabelItem[]): void;
  (e: 'update:crop', value: CropRect | null): void;
  (e: 'update:activeLabel', value: string): void;
}>();

type HoveredPolygonState = { labelId: string; contourIndex: number };
type DisplayContour = {
  key: string;
  labelId: string;
  contourIndex: number;
  contour: Point[];
  color: string;
  isActive: boolean;
  selectable: boolean;
};

const imageRef = ref<HTMLImageElement | null>(null);

watch(
  () => props.labels,
  (labels) => {
    const updated = labels.map(label => {
      // if user deletes all text, restore auto-generated text
      if (
        label.description.trim() === '' &&
        label.autoGenerated != null
      ) {
        return {
          ...label,
          autoGenerated: null,
        };
      }
      return label;
    });

    // Only emit if there is a real change, to avoid infinite loop
    const changed = updated.some((l, i) => l !== labels[i]);
    if (changed) {
      emit('update:labels', updated);
    }
  },
  { deep: true }
);

const hoveredPolygon = ref<HoveredPolygonState | null>(null);
const imageSize = ref({ width: 1, height: 1 });

const displayContours = computed<DisplayContour[]>(() =>
  props.labels.flatMap(label =>
    label.contours.map((contour, contourIndex) => ({
      key: `${label.id}-${contourIndex}`,
      labelId: label.id,
      contourIndex,
      contour,
      color: label.color,
      isActive: label.id === props.activeLabel,
      selectable: label.id !== props.activeLabel,
    }))
  )
);

const userStore = useUserStore();

const {
  canvasCursorClass,
  consumePolygonActivationSuppression,
  currentContour,
  currentCrop,
  draw,
  drawing,
  interactionHint,
  startDrawing,
  stopDrawing,
} = useImageLabelerInteraction({
  imageRef,
  activeLabel: toRef(props, 'activeLabel'),
  crop: toRef(props, 'crop'),
  onCropCommitted: (crop) => emit('update:crop', crop),
  onContourCommitted: (contour) => commitContour(contour),
});

const isHintCollapsed = computed(() => userStore.settings.imageLabelerHintCollapsed);

const hintBadgeLabel = computed(() => {
  if (interactionHint.value === 'Release to finish crop') return 'Cropping';
  if (interactionHint.value === 'Release to finish contour') return 'Drawing';
  if (props.activeLabel) return 'Ready';
  return 'Select';
});

const hintBadgeClass = computed(() => {
  if (interactionHint.value === 'Release to finish crop') {
    return 'bg-cyan-300/20 text-cyan-100 ring-1 ring-inset ring-cyan-200/30';
  }
  if (interactionHint.value === 'Release to finish contour') {
    return 'bg-emerald-300/20 text-emerald-100 ring-1 ring-inset ring-emerald-200/30';
  }
  if (props.activeLabel) {
    return 'bg-amber-300/20 text-amber-100 ring-1 ring-inset ring-amber-200/30';
  }
  return 'bg-white/10 text-white/80 ring-1 ring-inset ring-white/15';
});

function isHoveredPolygon(labelId: string, contourIndex: number) {
  return hoveredPolygon.value?.labelId === labelId && hoveredPolygon.value?.contourIndex === contourIndex;
}

function setHoveredPolygon(labelId: string, contourIndex: number) {
  if (props.activeLabel !== labelId) return;
  hoveredPolygon.value = { labelId, contourIndex };
}

function clearHoveredPolygon(labelId: string, contourIndex: number) {
  if (isHoveredPolygon(labelId, contourIndex)) {
    hoveredPolygon.value = null;
  }
}

function activateLabel(labelId: string) {
  if (props.activeLabel === labelId) return;
  hoveredPolygon.value = null;
  emit('update:activeLabel', labelId);
}

function maybeActivateLabel(labelId: string) {
  if (consumePolygonActivationSuppression()) {
    return;
  }
  activateLabel(labelId);
}

function withAlphaHex(color: string, alphaHex: string): string {
  const hex = color.trim();
  if (!/^#([0-9a-fA-F]{6})$/.test(hex)) return color;
  return `${hex}${alphaHex}`;
}

function getPolygonFillColor(labelId: string, contourIndex: number, baseColor: string) {
  const isActive = props.activeLabel === labelId;
  const isHoveredActive = isActive && isHoveredPolygon(labelId, contourIndex);
  const alpha = isHoveredActive ? 'AA' : isActive ? '77' : '44';
  return withAlphaHex(baseColor, alpha);
}

function getPolygonStrokeColor(labelId: string, contourIndex: number, baseColor: string) {
  const isActive = props.activeLabel === labelId;
  const isHoveredActive = isActive && isHoveredPolygon(labelId, contourIndex);
  const alpha = isHoveredActive ? 'FF' : isActive ? 'DD' : '77';
  return withAlphaHex(baseColor, alpha);
}

function getPolygonStrokeWidth(labelId: string, contourIndex: number) {
  const isActive = props.activeLabel === labelId;
  if (!isActive) return 1.2;
  return isHoveredPolygon(labelId, contourIndex) ? 3 : 2.2;
}

function removeContour(labelId: string, contourIndex: number) {
  const updatedLabels: LabelItem[] = props.labels.map(label => {
    if (label.id !== labelId) return label;
    return {
      ...label,
      contours: label.contours.filter((_, i) => i !== contourIndex),
    };
  });
  emit('update:labels', updatedLabels);
}

function handleDeleteHoveredPolygon(event: KeyboardEvent) {
  if (event.key !== 'Delete' && event.key !== 'Backspace') return;
  if (!hoveredPolygon.value) return;

  const activeElement = document.activeElement as HTMLElement | null;
  const tagName = activeElement?.tagName?.toLowerCase();
  const isEditable =
    activeElement?.isContentEditable ||
    tagName === 'input' ||
    tagName === 'textarea' ||
    tagName === 'select';
  if (isEditable) return;

  const { labelId, contourIndex } = hoveredPolygon.value;
  if (props.activeLabel !== labelId) return;
  removeContour(labelId, contourIndex);
  hoveredPolygon.value = null;
}

watch(() => props.activeLabel, (activeLabel) => {
  if (hoveredPolygon.value && hoveredPolygon.value.labelId !== activeLabel) {
    hoveredPolygon.value = null;
  }
});

onMounted(() => {
  window.addEventListener('keydown', handleDeleteHoveredPolygon);
});

onBeforeUnmount(() => {
  window.removeEventListener('keydown', handleDeleteHoveredPolygon);
});

function onImageLoad() {
  nextTick(() => {
    if (imageRef.value) {
      const { width, height } = imageRef.value.getBoundingClientRect();
      imageSize.value = { width, height };
    }
  });
}

function toSvgPoints(contour: Point[]): string {
  const { width, height } = imageSize.value;
  return contour.map(([x, y]) => `${x * width},${y * height}`).join(' ');
}

function getReactiveSvgPoints(contour: Point[]) {
  return computed(() => toSvgPoints(contour)).value;
}

function getReactiveCropPoints(crop: CropDraft | null) {
  if (!crop) return '';
  const contour: Point[] = [
    [Math.min(crop[0][0], crop[1][0]), Math.min(crop[0][1], crop[1][1])],
    [Math.max(crop[0][0], crop[1][0]), Math.min(crop[0][1], crop[1][1])],
    [Math.max(crop[0][0], crop[1][0]), Math.max(crop[0][1], crop[1][1])],
    [Math.min(crop[0][0], crop[1][0]), Math.max(crop[0][1], crop[1][1])],
    [Math.min(crop[0][0], crop[1][0]), Math.min(crop[0][1], crop[1][1])],
  ];
  return computed(() => toSvgPoints(contour)).value;
}

function commitContour(contour: Point[]) {
  if (!props.activeLabel) return;

  const updatedLabels: LabelItem[] = props.labels.map(label =>
    label.id === props.activeLabel
      ? { ...label, contours: [...label.contours, contour] }
      : label
  );
  emit('update:labels', updatedLabels);

  const label = updatedLabels.find(l => l.id === props.activeLabel);
  if (label && label.autoGenerated !== false) {
    autoGenerateRegionDescription(label);
  }
}

const dataStore = useDataStore();
const userStoreForAutoGen = userStore;
async function autoGenerateRegionDescription(label: LabelItem) {
  const settings = userStoreForAutoGen.settings
  if (!settings.enableAIAutoGen) {
    return
  }
  const fileName = dataStore.activeDataItem?.fileName;
  if (!fileName) return;

  const image_id = fileName.replace(/\.[^/.]+$/, '');

  try {
    const context = JSON.parse(JSON.stringify({
      ...dataStore.activeDataLabel,
    })) as DataLabel;
    // remove current label from context
    context.items = context.items.filter(item => item.id !== label.id);
    const res = await new AIBackendCalls().regionDescription(
      image_id, label.contours, context
    );
    console.log('Auto-complete response:', res)

    // Re-map based on the latest props.labels
    const finalLabels: LabelItem[] = props.labels.map(l =>
      l.id === label.id
        ? {
            ...l,
            description: res,
            autoGenerated: true,
          }
        : l
    );

    emit('update:labels', finalLabels);
  } catch (error) {
    console.error('Error fetching auto-complete:', error)
  }
}
</script>

<style scoped>
  img {
    -webkit-touch-callout: none;
  }
</style>
