<template>
  <div
    class="relative"

    @mousedown="startDrawing"
    @mousemove="draw"
    @mouseup="stopDrawing"

    @touchstart="startDrawing"
    @touchmove.prevent="draw"
    @touchend="stopDrawing"
  >
    <img
      ref="imageRef"
      :src="imageSrc"
      class="object-contain select-none"
      :style="{ maxHeight: `${maxHeight}px`, maxWidth: `${maxWidth}px`}"

      @load="onImageLoad"
      @dragstart.prevent
      @contextmenu="(event) => event.preventDefault()"
    />
    <svg
      ref="svgRef"
      class="absolute top-0 left-0 pointer-events-none"
      xmlns="http://www.w3.org/2000/svg"
      :width="imageSize.width"
      :height="imageSize.height"
    >
      <template v-if="!hideContours">
        <template v-for="label in nonActiveLabels" :key="label.id">
          <template v-for="(contour, contourIndex) in label.contours" :key="`${label.id}-${contourIndex}`">
            <polygon
              :points="getReactiveSvgPoints(contour)"
              :fill="getPolygonFillColor(label.id, contourIndex, label.color)"
              :stroke="getPolygonStrokeColor(label.id, contourIndex, label.color)"
              :stroke-width="getPolygonStrokeWidth(label.id, contourIndex)"
              fill-rule="evenodd"
            />
          </template>
        </template>
        <template v-if="activeLabelItem">
          <template v-for="(contour, contourIndex) in activeLabelItem.contours" :key="`${activeLabelItem.id}-${contourIndex}`">
            <polygon
              :points="getReactiveSvgPoints(contour)"
              :fill="getPolygonFillColor(activeLabelItem.id, contourIndex, activeLabelItem.color)"
              :stroke="getPolygonStrokeColor(activeLabelItem.id, contourIndex, activeLabelItem.color)"
              :stroke-width="getPolygonStrokeWidth(activeLabelItem.id, contourIndex)"
              fill-rule="evenodd"
              class="pointer-events-auto"
              @mouseenter="setHoveredPolygon(activeLabelItem.id, contourIndex)"
              @mouseleave="clearHoveredPolygon(activeLabelItem.id, contourIndex)"
            />
          </template>
        </template>
      </template>
      <polyline
        v-if="drawing && currentContour.length"
        :points="getReactiveSvgPoints(currentContour)"
        fill="none"
        :stroke="props.activeLabel ? props.labels.find(label => label.id === props.activeLabel)?.color : '#000000'"
        stroke-width="2"
      />
      <polyline
        :points="getReactiveCropPoints(currentCrop)"
        fill="none"
        stroke="#33EECC"
        stroke-width="2"
        stroke-dasharray="5,3"
      />
    </svg>
  </div>
</template>

<script lang="ts" setup>
import { ref, computed, nextTick, watch, onMounted, onBeforeUnmount } from 'vue';
import type { LabelItem } from '@/api';
import { AIBackendCalls } from '@/api'
import { resampleContour } from '@/utils';
import { useDataStore } from '@/stores/data';
import { useUserStore } from '@/stores/user'

const props = defineProps<{
  imageSrc: string;
  maxHeight: number;
  maxWidth: number;
  labels: LabelItem[];
  crop: [number, number, number, number] | null; // [x, y, width, height] in normalized coordinates [0,1]
  activeLabel: string | null;
  hideContours: boolean;
}>();

const emit = defineEmits<{
  (e: 'update:labels', value: LabelItem[]): void;
  (e: 'update:crop', value: [number, number, number, number] | null): void;
}>();

const imageRef = ref<HTMLImageElement | null>(null);
const svgRef = ref<SVGSVGElement | null>(null);

const cropping = ref(false);
// currentCrop is the crop rectangle being drawn in:
// [[point1.x, point1.y], [point2.x, point2.y]]
// the order is not important, but it should be normalized to [0,1] coordinates
const currentCrop = ref<[[number, number], [number, number]] | null>(null);
const currentCrop2RectFn = (v: [[number, number], [number, number]]) => {
  const [p1, p2] = v;
  return [
    [Math.min(p1[0], p2[0]), Math.min(p1[1], p2[1])],
    [Math.max(p1[0], p2[0]), Math.min(p1[1], p2[1])],
    [Math.max(p1[0], p2[0]), Math.max(p1[1], p2[1])],
    [Math.min(p1[0], p2[0]), Math.max(p1[1], p2[1])],
    [Math.min(p1[0], p2[0]), Math.min(p1[1], p2[1])],
  ] as [number, number][];
};
watch(() => props.crop, () => {
  console.log('crop prop changed', props.crop);
  if (!props.crop) {
    currentCrop.value = null;
    return;
  }
  const [x, y, width, height] = props.crop;
  currentCrop.value = [
    [x, y],
    [x + width, y + height]
  ];
}, { immediate: true });

watch(
  () => props.labels,
  (labels) => {
    const updated = labels.map(label => {
      // if user deletes all text, restore auto-generated text
      if (
        label.description.trim() === '' &&
        label.autoGenerated != null
      ) {
        return {
          ...label,
          autoGenerated: null,
        };
      }
      return label;
    });

    // Only emit if there is a real change, to avoid infinite loop
    const changed = updated.some((l, i) => l !== labels[i]);
    if (changed) {
      emit('update:labels', updated);
    }
  },
  { deep: true }
);

const drawing = ref(false);
const currentContour = ref<[number, number][]>([]);
const hoveredPolygon = ref<{ labelId: string; contourIndex: number } | null>(null);
const activeLabelItem = computed(() => props.labels.find(label => label.id === props.activeLabel) ?? null);
const nonActiveLabels = computed(() => props.labels.filter(label => label.id !== props.activeLabel));

const imageLoaded = ref(false);
const imageSize = ref({ width: 1, height: 1 });

function isHoveredPolygon(labelId: string, contourIndex: number) {
  return hoveredPolygon.value?.labelId === labelId && hoveredPolygon.value?.contourIndex === contourIndex;
}

function setHoveredPolygon(labelId: string, contourIndex: number) {
  if (props.activeLabel !== labelId) return;
  hoveredPolygon.value = { labelId, contourIndex };
}

function clearHoveredPolygon(labelId: string, contourIndex: number) {
  if (isHoveredPolygon(labelId, contourIndex)) {
    hoveredPolygon.value = null;
  }
}

function withAlphaHex(color: string, alphaHex: string): string {
  const hex = color.trim();
  if (!/^#([0-9a-fA-F]{6})$/.test(hex)) return color;
  return `${hex}${alphaHex}`;
}

function getPolygonFillColor(labelId: string, contourIndex: number, baseColor: string) {
  const isActive = props.activeLabel === labelId;
  const isHoveredActive = isActive && isHoveredPolygon(labelId, contourIndex);
  const alpha = isHoveredActive ? 'AA' : isActive ? '77' : '44';
  return withAlphaHex(baseColor, alpha);
}

function getPolygonStrokeColor(labelId: string, contourIndex: number, baseColor: string) {
  const isActive = props.activeLabel === labelId;
  const isHoveredActive = isActive && isHoveredPolygon(labelId, contourIndex);
  const alpha = isHoveredActive ? 'FF' : isActive ? 'DD' : '77';
  return withAlphaHex(baseColor, alpha);
}

function getPolygonStrokeWidth(labelId: string, contourIndex: number) {
  const isActive = props.activeLabel === labelId;
  if (!isActive) return 1.2;
  return isHoveredPolygon(labelId, contourIndex) ? 3 : 2.2;
}

function removeContour(labelId: string, contourIndex: number) {
  const updatedLabels: LabelItem[] = props.labels.map(label => {
    if (label.id !== labelId) return label;
    return {
      ...label,
      contours: label.contours.filter((_, i) => i !== contourIndex),
    };
  });
  emit('update:labels', updatedLabels);
}

function handleDeleteHoveredPolygon(event: KeyboardEvent) {
  if (event.key !== 'Delete' && event.key !== 'Backspace') return;
  if (!hoveredPolygon.value) return;

  const activeElement = document.activeElement as HTMLElement | null;
  const tagName = activeElement?.tagName?.toLowerCase();
  const isEditable =
    activeElement?.isContentEditable ||
    tagName === 'input' ||
    tagName === 'textarea' ||
    tagName === 'select';
  if (isEditable) return;

  const { labelId, contourIndex } = hoveredPolygon.value;
  if (props.activeLabel !== labelId) return;
  removeContour(labelId, contourIndex);
  hoveredPolygon.value = null;
}

watch(() => props.activeLabel, (activeLabel) => {
  if (hoveredPolygon.value && hoveredPolygon.value.labelId !== activeLabel) {
    hoveredPolygon.value = null;
  }
});

onMounted(() => {
  window.addEventListener('keydown', handleDeleteHoveredPolygon);
});

onBeforeUnmount(() => {
  window.removeEventListener('keydown', handleDeleteHoveredPolygon);
});

function onImageLoad() {
  nextTick(() => {
    if (imageRef.value) {
      const { width, height } = imageRef.value.getBoundingClientRect();
      imageSize.value = { width, height };
    }
    imageLoaded.value = true;
  });
}

function toSvgPoints(contour: [number, number][]): string {
  const { width, height } = imageSize.value;
  return contour.map(([x, y]) => `${x * width},${y * height}`).join(' ');
}

function getReactiveSvgPoints(contour: [number, number][]) {
  return computed(() => toSvgPoints(contour)).value;
}

function getReactiveCropPoints(crop: [[number, number], [number, number]] | null) {
  if (!crop) return '';
  return computed(() => {
    const contourPts = currentCrop2RectFn(crop);
    return toSvgPoints(contourPts);
  }).value;
}

function getNormalizedCoordinates(event: MouseEvent | TouchEvent): [number, number] {
  const img = imageRef.value;
  if (!img) return [0, 0];
  const rect = img.getBoundingClientRect();
  let x = 0;
  let y = 0;
  if (event instanceof MouseEvent) {
    x = (event.clientX - rect.left) / rect.width;
    y = (event.clientY - rect.top) / rect.height;
  }
  else if (event instanceof TouchEvent && event.touches.length > 0) {
    x = (event.touches[0]!.clientX - rect.left) / rect.width;
    y = (event.touches[0]!.clientY - rect.top) / rect.height;
  }
  return [x, y];
}

function startDrawing(event: MouseEvent | TouchEvent) {
  if (
    (
      (event instanceof MouseEvent && event.button === 0) ||
      (event instanceof TouchEvent && event.touches.length === 1)
    )
    && props.activeLabel) {
    // left click initiates drawing
    drawing.value = true;
    currentContour.value = [getNormalizedCoordinates(event)];
    console.log('startDrawing', event);
  }
  else if ( event instanceof MouseEvent && event.button == 2) {
    // right click initiates crop
    event.preventDefault();
    const [x, y] = getNormalizedCoordinates(event);
    if (props.crop) { // If crop already exists, reset it
      console.log('resetCrop');
      emit('update:crop', null);
    }
    else { // Start a new crop
      console.log('startCrop', event);
      cropping.value = true;
      currentCrop.value = [[x, y], [x, y]]; // start crop at the clicked point
    }
  }
}

function draw(event: MouseEvent | TouchEvent) {
  // if (!drawing.value) return;
  if (drawing.value) {
    currentContour.value.push(getNormalizedCoordinates(event));
  }
  if (cropping.value && currentCrop.value) {
    const [x, y] = getNormalizedCoordinates(event);
    if (currentCrop.value) {
      currentCrop.value[1] = [x, y]; // update the second point of the crop rectangle
    }
  }
}

function stopDrawing() {
  if (drawing.value && props.activeLabel) {
    // finalize the contour
    drawing.value = false;

    const resampledContour = resampleContour(currentContour.value);
    // check if resampledContour has at least some points
    const area = Math.abs(resampledContour.reduce((acc, point, index) => {
      const nextPoint = resampledContour[(index + 1) % resampledContour.length];
      return acc + (point[0] * nextPoint![1] - nextPoint![0] * point[1]);
    }, 0)) / 2;
    if (area < 1e-4) {
      currentContour.value = [];
      console.warn('Contour area too small, ignoring');
      return;
    }

    const updatedLabels: LabelItem[] = props.labels.map(label =>
      label.id === props.activeLabel
        ? { ...label, contours: [...label.contours, resampledContour] }
        : label
    );
    emit('update:labels', updatedLabels);

    const label = updatedLabels.find(l => l.id === props.activeLabel);
    if (label && label.autoGenerated !== false) {
      autoGenerateRegionDescription(label);
    }

    currentContour.value = [];
  }

  if (cropping.value && currentCrop.value) {
    // If crop is finalized, we can emit the crop update
    console.log('finalizeCrop');
    cropping.value = false;
    const crop = [
      Math.min(currentCrop.value[0][0], currentCrop.value[1][0]),
      Math.min(currentCrop.value[0][1], currentCrop.value[1][1]),
      Math.abs(currentCrop.value[1][0] - currentCrop.value[0][0]),
      Math.abs(currentCrop.value[1][1] - currentCrop.value[0][1])
    ] as [number, number, number, number];
    currentCrop.value = null;
    const MIN_CROP_SIZE = 0.05; // minimum size for crop to be valid
    if (crop[2] < MIN_CROP_SIZE || crop[3] < MIN_CROP_SIZE) {
      console.warn('Crop too small, resetting');
      emit('update:crop', null);
    }
    else{
      emit('update:crop', crop);
    }
  }
}

const dataStore = useDataStore();
async function autoGenerateRegionDescription(label: LabelItem) {
  const userStore = useUserStore()
  const settings = userStore.settings
  if (!settings.enableAIAutoGen) {
    return
  }
  const fileName = dataStore.activeDataItem?.fileName;
  if (!fileName) return;

  const image_id = fileName.replace(/\.[^/.]+$/, '');

  try {
    const res = await new AIBackendCalls().regionDescription(
      image_id, label.contours,
    );
    console.log('Auto-complete response:', res)

    // Re-map based on the latest props.labels
    const finalLabels: LabelItem[] = props.labels.map(l =>
      l.id === label.id
        ? {
            ...l,
            description: res,
            autoGenerated: true,
          }
        : l
    );

    emit('update:labels', finalLabels);
  } catch (error) {
    console.error('Error fetching auto-complete:', error)
  }
}
</script>

<style scoped>
  img {
    -webkit-touch-callout: none;
  }
</style>
