<script lang="ts" setup>
  import { computed, ref, watch, nextTick, onMounted, onUnmounted, type ComponentPublicInstance } from 'vue';
  import ImageLabeler from './ImageLabeler.vue';
  import ImageLabelerContourToggle from './ImageLabelerContourToggle.vue';
  import BooleanPillToggle from './BooleanPillToggle.vue';
  import LabelItemInput from './LabelItemInput.vue';
  import FloatingHint from './containers/FloatingHint.vue';
  import { useDataStore } from '@/stores/data';
  import { useComponentStore } from '@/stores/component';
  import { useUiStateStore } from '@/stores/uistate';
  import { useUserStore } from '@/stores/user';
  import { useTranscriptRecorder } from '@/composables/useTranscriptRecorder';
  import { useProgressHint } from '@/composables/useProgressHint';
  import DescInput from './DescInput.vue';
  import { AIService, type DataLabel, type LabelItem, FileLabelStatus } from '@/api';
  import { resampleContour } from '@/contour-tools';

  type ContourVisibilityMode = 'none' | 'active' | 'all';
  const nextModeMap: Record<ContourVisibilityMode, ContourVisibilityMode> = {
    none: 'active',
    active: 'all',
    all: 'none',
  };

  const dataStore = useDataStore();
  const componentStore = useComponentStore();
  const uiStateStore = useUiStateStore();
  const userStore = useUserStore();
  type LabelItemInputInstance = InstanceType<typeof LabelItemInput>;
  const activeLabel = ref<string>("");
  const unsavedChanges = ref(false);
  const contourVisibilityMode = ref<ContourVisibilityMode>('all');
  const loading = ref(false);
  const OVERALL_DESCRIPTION_TRANSCRIPT_TARGET = 'overall-description';
  const imageMaxW = ref(800);
  const regionReferringProgressHint = useProgressHint('Region Referring');
  const regionReferringProgress = regionReferringProgressHint.progress;
  const regionProposalProgressHint = useProgressHint('Region Proposal');
  const regionProposalProgress = regionProposalProgressHint.progress;
  const regionProposalBusy = ref(false);
  const labelItemRefs = ref<Record<string, LabelItemInputInstance | null>>({});
  const transcriptRecorder = useTranscriptRecorder();

  const isTranscriptEnabled = computed(() => userStore.settings.enableAIHelpers && userStore.settings.aiFeatureSet.transcript);

  function cycleContourVisibilityMode() {
    contourVisibilityMode.value = nextModeMap[contourVisibilityMode.value];
  }

  const imageContainer = ref<HTMLDivElement | null>(null);

  {
    const handleResize = () => {
      updateImageMaxW();
    };

    function updateImageMaxW() {
      if (imageContainer.value) {
        const { width } = imageContainer.value.getBoundingClientRect();
        imageMaxW.value = Math.min(width - 20, 800); // 20px for padding
      }
    }
    watch( () => imageContainer.value, (newValue) => { if (newValue) { updateImageMaxW(); } });
    onMounted(() => { window.addEventListener('resize', handleResize); })
    onUnmounted(() => { window.removeEventListener('resize', handleResize); });
  }

  watch(
    () => dataStore.activeDataLabel,
    (newLabel) => {
      nextTick(() => {
        if (newLabel) {
          activeLabel.value = newLabel.items[0]?.id || "";
        }
        unsavedChanges.value = false;
      });
    },
    { immediate: true }
  );
  // deep watch for unsaved changes
  watch(
    () => dataStore.activeDataLabel,
    () => {
      if (!dataStore.activeDataLabel) return;
      unsavedChanges.value = true;
      // console.log("activeLabel altered", dataStore.activeDataLabel);
    },
    { immediate: true, deep: true }
  );

  const predefinedColorsScheme = [
    '#FF5733', '#33FF57', '#3357FF', '#F1C40F', '#8E44AD',
    '#E74C3C', '#3498DB', '#2ECC71', '#9B59B6', '#34495E',
  ];

  function makeNewLabelItem(description = '', autoGenerated: boolean | null = null): LabelItem {
    const itemCount = dataStore.activeDataLabel?.items.length ?? 0;
    return {
      id: Date.now().toString() + Math.random().toString(36).substring(2),
      lowConfidence: false,
      description,
      color: itemCount < predefinedColorsScheme.length
        ? predefinedColorsScheme[itemCount]
        : '#' + Math.floor(Math.random() * 16777215).toString(16),
      contours: [],
      autoGenerated,
      preRefineContours: null,
    } as LabelItem;
  }

  function cloneContours(contours: [number, number][][]): [number, number][][] {
    return contours.map(contour => contour.map(point => [...point] as [number, number]));
  }

  function focusOnLabelItem(id: string) {
    const labelItem = document.getElementById('label-item-' + id) as HTMLDivElement;
    if (labelItem) {
      labelItem.scrollIntoView({ behavior: 'smooth', block: 'center' });
      labelItemRefs.value[id]?.focusInput();
    }
  }

  function setLabelItemRef(id: string, instance: LabelItemInputInstance | null) {
    if (instance) {
      labelItemRefs.value[id] = instance;
      return;
    }

    delete labelItemRefs.value[id];
  }

  function bindLabelItemRef(id: string) {
    return (instance: Element | ComponentPublicInstance | null) => {
      setLabelItemRef(id, instance as LabelItemInputInstance | null);
    };
  }

  function showTranscriptError(context: string, error: unknown) {
    console.error(`Error transcribing ${context}:`, error);
    uiStateStore.msg.set(
      error instanceof Error ? error.message : String(error),
      'warning'
    );
  }

  async function handleTranscriptRequest(
    targetId: string,
    options: {
      startMessage: string
      successMessage: string
      errorContext: string
      onRecordingStarted?: () => void
      applyTranscript: (transcript: string) => void | Promise<void>
    }
  ) {
    if (!isTranscriptEnabled.value) {
      return;
    }

    try {
      const result = await transcriptRecorder.toggleTargetTranscript(targetId);
      if (result.status === 'recording-started') {
        options.onRecordingStarted?.();
        uiStateStore.msg.set(options.startMessage, 'info');
        return;
      }

      await options.applyTranscript(result.transcript);
      uiStateStore.msg.set(options.successMessage, 'info');
    }
    catch (error) {
      showTranscriptError(options.errorContext, error);
    }
  }

  async function handleLabelTranscript(label: LabelItem) {
    await handleTranscriptRequest(label.id, {
      startMessage: 'Recording audio for label transcription. Click the mic again to stop.',
      successMessage: 'Transcript inserted into label input.',
      errorContext: 'label audio',
      onRecordingStarted: () => {
        activeLabel.value = label.id;
      },
      applyTranscript: async (transcript) => {
        const targetLabel = dataStore.activeDataLabel?.items.find(item => item.id === label.id);
        if (!targetLabel) {
          throw new Error('Target label no longer exists.');
        }

        targetLabel.description = transcript;
        targetLabel.autoGenerated = false;
        activeLabel.value = label.id;

        await nextTick();
        focusOnLabelItem(label.id);
      },
    });
  }

  async function handleDescTranscript() {
    await handleTranscriptRequest(OVERALL_DESCRIPTION_TRANSCRIPT_TARGET, {
      startMessage: 'Recording audio for overall description. Click the mic again to stop.',
      successMessage: 'Transcript inserted into overall description.',
      errorContext: 'overall description audio',
      applyTranscript: (transcript) => {
        componentStore.descInputExpose?.insertTranscriptAtCursor(transcript);
      },
    });
  }

  async function cancelTranscriptRecording() {
    await transcriptRecorder.cancelRecording();
  }

  function newLabelItem() {
    const item = makeNewLabelItem();
    dataStore.activeDataLabel?.items.push(item);
    activeLabel.value = item.id;
    // focus on the new label item text input
    nextTick(() => {
      focusOnLabelItem(item.id);
    });
  }

  function moveLabelItemByOffset(id: string, offset: -1 | 1) {
    const items = dataStore.activeDataLabel?.items;
    if (!items || items.length < 2) {
      return;
    }

    const fromIndex = items.findIndex((item) => item.id === id);
    if (fromIndex === -1) {
      return;
    }

    const toIndex = fromIndex + offset;
    if (toIndex < 0 || toIndex >= items.length) {
      return;
    }

    const [moved] = items.splice(fromIndex, 1);
    items.splice(toIndex, 0, moved!);
    activeLabel.value = id;

    nextTick(() => {
      focusOnLabelItem(id);
    });
  }

  function handleMoveLabelUp(id: string) {
    moveLabelItemByOffset(id, -1);
  }

  function handleMoveLabelDown(id: string) {
    moveLabelItemByOffset(id, 1);
  }

  async function proposeRegionDescriptions() {
    const fileName = dataStore.activeDataItem?.fileName;
    const activeDataLabel = dataStore.activeDataLabel;
    if (!fileName || !activeDataLabel) {
      return;
    }

    if (regionProposalBusy.value) {
      return;
    }

    const aiService = new AIService();
    const imageId = fileName.replace(/\.[^/.]+$/, '');

    try {
      regionProposalBusy.value = true;
      regionProposalProgressHint.show({
        body: 'Discovering possible abnormal regions from this image...',
        busy: true,
      });

      const descriptions = (await aiService.regionDescriptionPropose(imageId, activeDataLabel))
        .map((description) => description.trim())
        .filter(Boolean);

      if (descriptions.length === 0) {
        regionProposalProgressHint.show({
          body: 'No region description proposals were returned.',
          tone: 'error',
          autoHideMs: 2000,
        });
        return;
      }

      const existingDescriptions = new Set(
        activeDataLabel.items.map((item) => item.description.trim()).filter(Boolean)
      );

      let nInserted = 0;
      descriptions.forEach((description) => {
        if (existingDescriptions.has(description)) {
          return;
        }
        const newItem = makeNewLabelItem(description, true);
        if (nInserted === 0) {
          focusOnLabelItem(newItem.id);
        }
        activeDataLabel.items.push(newItem);
        activeLabel.value = newItem.id;
        nInserted++;
      });

      regionProposalProgressHint.show({
        body: `Inserted ${nInserted} proposed label${nInserted === 1 ? '' : 's'}.`,
        tone: 'success',
        autoHideMs: 1800,
      });
    }
    catch (error) {
      console.error('Error proposing region descriptions:', error);
      regionProposalProgressHint.show({
        title: 'Region Proposal Failed',
        body: error instanceof Error ? error.message : String(error),
        tone: 'error',
        autoHideMs: 2600,
      });
    }
    finally {
      regionProposalBusy.value = false;
    }
  }

  async function handleContourCommitted(payload: { label: LabelItem; labels: LabelItem[] }) {
    if (
      payload.label.autoGenerated === false ||
      !userStore.settings.enableAIHelpers ||
      !userStore.settings.aiFeatureSet.regionDescriptionOnDraw
    ) {
      return;
    }

    const fileName = dataStore.activeDataItem?.fileName;
    const activeDataLabel = dataStore.activeDataLabel;
    if (!fileName || !activeDataLabel) {
      return;
    }

    const imageId = fileName.replace(/\.[^/.]+$/, '');
    const context = JSON.parse(JSON.stringify({
      ...activeDataLabel,
      items: payload.labels,
    })) as DataLabel;
    context.items = context.items.filter(item => item.id !== payload.label.id);

    try {
      const description = await new AIService().regionDescription(
        imageId,
        payload.label.contours,
        context
      );

      const targetLabel = dataStore.activeDataLabel?.items.find(item => item.id === payload.label.id);
      if (!targetLabel) {
        return;
      }

      targetLabel.description = description;
      targetLabel.autoGenerated = true;
    }
    catch (error) {
      console.error('Error fetching auto-complete:', error);
    }
  }

  async function handleContourDbclick(payload: { label: LabelItem; labels: LabelItem[] }) {
    if (
      !userStore.settings.enableAIHelpers ||
      !userStore.settings.aiFeatureSet.regionRefineOnDoubleClick
    ) {
      return;
    }

    const fileName = dataStore.activeDataItem?.fileName;
    if (!fileName || payload.label.contours.length === 0) {
      return;
    }

    const imageId = fileName.replace(/\.[^/.]+$/, '');

    try {
      const contours = await new AIService().regionRefine(imageId, payload.label.contours);
      const targetLabel = dataStore.activeDataLabel?.items.find(item => item.id === payload.label.id);
      if (!targetLabel) {
        return;
      }
      targetLabel.preRefineContours = cloneContours(payload.label.contours);
      targetLabel.contours = contours.map(contour => resampleContour(contour));
    }
    catch (error) {
      console.error('Error refining contours:', error);
    }
  }

  async function handleRegionReferring(payload: { label: LabelItem; labels: LabelItem[] }) {
    if (
      !userStore.settings.enableAIHelpers ||
      !userStore.settings.aiFeatureSet.regionReferringOnEnter
    ) {
      return;
    }

    const fileName = dataStore.activeDataItem?.fileName;
    if (!fileName) {
      return;
    }

    const prompt = payload.label.description.trim();
    if (!prompt) {
      return;
    }

    const imageId = fileName.replace(/\.[^/.]+$/, '');

    try {
      regionReferringProgressHint.show({
        body: 'Generating segmentation from your description...',
        busy: true,
      });

      const contours = await new AIService().regionReferring(imageId, prompt);
      const targetLabel = dataStore.activeDataLabel?.items.find(item => item.id === payload.label.id);
      if (!targetLabel) {
        regionReferringProgressHint.show({
          body: 'Target label changed before update was applied.',
          tone: 'error',
          autoHideMs: 1800,
        });
        return;
      }
      targetLabel.contours = contours.map(contour => resampleContour(contour));
      regionReferringProgressHint.show({
        body: `Segmentation updated (${contours.length} contour${contours.length === 1 ? '' : 's'}).`,
        tone: 'success',
        autoHideMs: 1500,
      });
    }
    catch (error) {
      console.error('Error referring contours:', error);
      regionReferringProgressHint.show({
        title: 'Region Referring Failed',
        body: error instanceof Error ? error.message : String(error),
        tone: 'error',
        autoHideMs: 2500,
      });
    }
  }

  function restoreContourBackup() {
    if (!activeLabel.value) {
      return;
    }

    const targetLabel = dataStore.activeDataLabel?.items.find(item => item.id === activeLabel.value);
    if (!targetLabel) {
      return;
    }

    if (!targetLabel.preRefineContours) {
      return;
    }

    targetLabel.contours = cloneContours(targetLabel.preRefineContours);
    targetLabel.preRefineContours = null;
  }

  async function saveAndNext() {
    if (unsavedChanges.value) {
      await save();
    }
    await dataStore.loadNextDataItem();
  }

  async function save() {
    console.log("Saving label...");
    if (dataStore.activeDataLabel == null){
      return;
    }
    else{
      console.log("Saving label");
    }
    try {
      loading.value = true;
      await dataStore.saveCurrentLabel();
      unsavedChanges.value = false;
      await dataStore.refreshActiveDataItem();
    }
    catch (error) {
      console.error("Error saving label:", error);
      alert("Error saving label: " + error);
    }
    finally {
      loading.value = false;
    }
  }

  async function skipAndNext (){
    if (dataStore.activeDataLabel == null){
      return;
    }
    // get reason from user
    const reason = prompt("Please enter a reason for skipping this item:", "No reason");
    if (reason == null || reason.trim() === "") {
      return;
    }
    await dataStore.skipActiveData(reason);
    await dataStore.refreshActiveDataItem();
    unsavedChanges.value = false;
    try { loading.value = true; dataStore.loadNextDataItem(); }
    catch (error) { throw error; }
    finally { loading.value = false; }
  }

  async function unSkip (){
    if (dataStore.activeDataLabel == null){
      return;
    }
    await dataStore.unskipActiveData();
    await dataStore.refreshActiveDataItem();
    unsavedChanges.value = false;
  }


  {
    const saveHandler = async (event: KeyboardEvent) => {
      if ((event.ctrlKey || event.metaKey || event.altKey) && event.key === 's') {
        event.preventDefault(); await save();
      }
    };
    const saveAndNextHandler = async (event: KeyboardEvent) => {
      if (event.altKey && event.key === 'n') {
        event.preventDefault(); await saveAndNext();
      }
    };
    const skipHandler = async (event: KeyboardEvent) => {
      if (event.altKey && event.key === 'q') {
        event.preventDefault(); await skipAndNext();
      }
    };
    const tabHandler = async (event: KeyboardEvent) => {
      // Tab to create new label item if no label items exist
      // If label item is active and it's input is not selected, select the input.
      if (event.key === 'Tab') {
        if (dataStore.activeDataLabel?.items.length === 0) {
          event.preventDefault();
          newLabelItem();
          return;
        }

        const isFocusedOnActiveLabelInput = (() => {
          const activeElement = document.activeElement as HTMLElement;
          if (activeElement.tagName.toLowerCase() === 'input') {
            const parent = activeElement.closest('#label-item-' + activeLabel.value);
            if (parent) { return true; }
          }
          return false;
        })();

        if (!isFocusedOnActiveLabelInput) {
          // focus on the active label item input
          console.log('Focusing on active label item input:', activeLabel.value);
          event.preventDefault();
          focusOnLabelItem(activeLabel.value);
          return;
        }

      }
    };
    onMounted(() => {
      window.addEventListener('keydown', saveHandler);
      window.addEventListener('keydown', saveAndNextHandler);
      window.addEventListener('keydown', skipHandler);
      window.addEventListener('keydown', tabHandler);
    });
    onUnmounted(() => {
      window.removeEventListener('keydown', saveHandler);
      window.removeEventListener('keydown', saveAndNextHandler);
      window.removeEventListener('keydown', skipHandler);
      window.removeEventListener('keydown', tabHandler);
      cancelTranscriptRecording();
      transcriptRecorder.dispose();
      regionReferringProgressHint.dispose();
      regionProposalProgressHint.dispose();
    });
  }

</script>

<template>
  <div :class="'flex flex-col gap-4 p-4 bg-white shadow-md rounded-lg' + (loading ? ' opacity-50 pointer-events-none' : '')" v-if="!uiStateStore.labelPanelLoading">

    <div class="flex justify-center items-center p-4 w-full rounded-lg bg-gray-100" ref="imageContainer">
      <div class="relative" v-if="dataStore.activeDataItem && dataStore.activeDataLabel">
        <ImageLabelerContourToggle
          :mode="contourVisibilityMode"
          @cycle="cycleContourVisibilityMode"
        />
        <ImageLabeler
          :imageSrc="dataStore.activeDataItem.imageUrl"
          :max-height="600"
          :max-width="imageMaxW"
          v-model:labels="dataStore.activeDataLabel.items"
          v-model:crop="dataStore.activeDataLabel.crop"
          v-model:activeLabel="activeLabel"
          :contourVisibilityMode="contourVisibilityMode"
          @contour-committed="handleContourCommitted"
          @contour-dbclick="handleContourDbclick"
          @restore-contour-backup="restoreContourBackup"
          >
        </ImageLabeler>
      </div>
      <p v-else class="text-gray-500 text-lg">
        Select an image to start labeling
      </p>
    </div>

    <DescInput
      v-if="dataStore.activeDataItem && dataStore.activeDataLabel"
      v-model="dataStore.activeDataLabel.overallDescription"
      :transcript-enabled="isTranscriptEnabled"
      :transcript-busy="transcriptRecorder.isBusyForTarget(OVERALL_DESCRIPTION_TRANSCRIPT_TARGET)"
      :transcript-recording="transcriptRecorder.isRecordingForTarget(OVERALL_DESCRIPTION_TRANSCRIPT_TARGET)"
      @transcribe="handleDescTranscript"
      @enter="if (dataStore.activeDataLabel!.items.length > 0) {
        const id = dataStore.activeDataLabel!.items[0]!.id;
        focusOnLabelItem(id)
      }
      else {
        newLabelItem()
      }"
    ></DescInput>

    <div
      v-if="dataStore.activeDataItem && dataStore.activeDataLabel"
      class="flex items-center justify-between rounded-xl border border-gray-200 bg-gray-50/70 px-3 py-2"
    >
      <div class="text-sm text-gray-600">
        Abnormality discovery status
      </div>
      <BooleanPillToggle
        v-model="dataStore.activeDataLabel.abnormalityExhausted"
        true-label="Exhausted"
        false-label="More Possible"
        true-title="All abnormalities are already fully annotated"
        false-title="There may still be unlabeled abnormalities"
      />
    </div>

    <div v-if="dataStore.activeDataItem && dataStore.activeDataLabel" class="flex flex-col gap-3">
      <div class="relative">
        <FloatingHint
          v-if="regionReferringProgress.show"
          :title="regionReferringProgress.title"
          :body="regionReferringProgress.body"
          :tone="regionReferringProgress.tone"
          :busy="regionReferringProgress.busy"
          @close="regionReferringProgressHint.hide()"
        />
        <FloatingHint
          v-if="regionProposalProgress.show"
          :title="regionProposalProgress.title"
          :body="regionProposalProgress.body"
          :tone="regionProposalProgress.tone"
          :busy="regionProposalProgress.busy"
          @close="regionProposalProgressHint.hide()"
        />
      </div>
      <template
        v-for="(label, index) in dataStore.activeDataLabel.items" :key="label.id"
      >
        <LabelItemInput
          :ref="bindLabelItemRef(label.id)"
          v-model="dataStore.activeDataLabel.items[index]!"
          :active-contour-id="activeLabel"
          :transcript-enabled="isTranscriptEnabled"
          :transcript-busy="transcriptRecorder.isBusyForTarget(label.id)"
          :transcript-recording="transcriptRecorder.isRecordingForTarget(label.id)"
          @enter="handleRegionReferring({ label, labels: dataStore.activeDataLabel!.items })"
          @transcribe="handleLabelTranscript(label)"
          @move-up="handleMoveLabelUp"
          @move-down="handleMoveLabelDown"
          @delete="(id: string) => {
            const itemIndex = dataStore.activeDataLabel!.items.findIndex(item => item.id === id);
            if (itemIndex !== -1) {
              dataStore.activeDataLabel!.items.splice(itemIndex, 1);
            }
            // focus on the next item if exists, otherwise focus on the previous item
            if (dataStore.activeDataLabel!.items.length > 0) {
              const nextIndex = itemIndex < dataStore.activeDataLabel!.items.length ? itemIndex : itemIndex - 1;
              activeLabel = dataStore.activeDataLabel!.items[nextIndex]!.id;
              focusOnLabelItem(activeLabel);
            }
          }"
          @select="(id) => activeLabel = id"
          @select-previous="() => {
            if (index - 1 >= 0) {
              activeLabel = dataStore.activeDataLabel!.items[index - 1]!.id;
              focusOnLabelItem(activeLabel);
            }
          }"
          @select-next="() => {
            if (index + 1 < dataStore.activeDataLabel!.items.length) {
              activeLabel = dataStore.activeDataLabel!.items[index + 1]!.id;
              focusOnLabelItem(activeLabel);
            }
            else {
              newLabelItem();
            }
          }"
          :id="'label-item-' + label.id"
        />
      </template>
    </div>

    <div class="flex justify-center gap-3" v-if="dataStore.activeDataItem && dataStore.activeDataLabel">
      <button
        @click="newLabelItem"
        class="text-gray-700 bg-white hover:bg-gray-100 font-bold rounded-lg text-lg py-2 flex justify-center items-center shadow-md w-full"
      >
        +
      </button>
      <button
        v-if="userStore.settings.enableAIHelpers && userStore.settings.aiFeatureSet.regionDescriptionProposal"
        @click="proposeRegionDescriptions"
        :disabled="regionProposalBusy"
        class="h-full w-15 rounded-lg border border-gray-200 bg-white text-gray-500 hover:text-sky-700 hover:bg-gray-50 shadow-sm flex items-center justify-center disabled:opacity-50 disabled:cursor-not-allowed"
        aria-label="Propose region descriptions"
        title="Propose region descriptions from the image"
      >
        <svg class="h-5 w-5" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
          <path d="M12 2c4.6 0 8.2 3.6 8.2 8 0 2.2-.9 4-2.6 5.7-1.4 1.4-3.1 2.5-4.8 3.9-.3.2-.6.7-.8 1.1-.2-.4-.5-.9-.8-1.1-1.7-1.4-3.4-2.5-4.8-3.9C4.7 14 3.8 12.2 3.8 10c0-4.4 3.6-8 8.2-8z" />
          <circle cx="12" cy="10" r="2.2" class="text-white" fill="white" />
        </svg>
      </button>
    </div>

    <!-- Save button -->
    <div class="flex justify-center w-full gap-2"
    >
      <button
        v-if="dataStore.activeDataLabel && dataStore.activeDataItem?.status != FileLabelStatus.SKIPPED"
        @click="skipAndNext"
       class="text-white bg-yellow-600 hover:bg-yellow-700 font-bold rounded-xl text-lg py-2 flex justify-center items-center shadow-md max-w-1/4 w-sm">
        Skip & Next
      </button>
      <button
        v-if="dataStore.activeDataLabel && dataStore.activeDataItem?.status == FileLabelStatus.SKIPPED"
        @click="unSkip"
       class="text-white bg-yellow-600 hover:bg-yellow-700 font-bold rounded-xl text-lg py-2 flex justify-center items-center shadow-md max-w-1/4 w-sm">
        Un-Skip
      </button>

      <button
        v-if="unsavedChanges"
        @click="save"
        class="text-white bg-blue-600 hover:bg-blue-700 font-bold rounded-xl text-lg py-2 flex justify-center items-center shadow-md max-w-1/2 w-lg"
      >
        Save
      </button>
      <button
        @click="saveAndNext"
        class="text-white bg-blue-600 hover:bg-blue-700 font-bold rounded-xl text-lg py-2 flex justify-center items-center shadow-md max-w-1/2 w-lg"
      >
        {{ unsavedChanges ? 'Save & Next' : 'Next' }}
      </button>
    </div>

  </div>
  <div v-else class="flex justify-center items-center p-8 w-full rounded-lg bg-gray-100">
    <div class="text-gray-500 text-lg animate-pulse">
      Loading...
    </div>
  </div>

</template>
