<script lang="ts" setup>
  import { ref, watch, nextTick, onMounted, onUnmounted } from 'vue';
  import ImageLabeler from './ImageLabeler.vue';
  import ImageLabelerContourToggle from './ImageLabelerContourToggle.vue';
  import LabelItemInput from './LabelItemInput.vue';
  import { useDataStore } from '@/stores/data';
  import { useUiStateStore } from '@/stores/uistate';
  import { useUserStore } from '@/stores/user';
  import DescInput from './DescInput.vue';
  import { AIService, type DataLabel, type LabelItem, FileLabelStatus } from '@/api';
  import { resampleContour } from '@/contour-tools';

  type ContourVisibilityMode = 'none' | 'active' | 'all';
  const nextModeMap: Record<ContourVisibilityMode, ContourVisibilityMode> = {
    none: 'active',
    active: 'all',
    all: 'none',
  };

  const dataStore = useDataStore();
  const uiStateStore = useUiStateStore();
  const userStore = useUserStore();
  const activeLabel = ref<string>("");
  const unsavedChanges = ref(false);
  const contourVisibilityMode = ref<ContourVisibilityMode>('all');
  const loading = ref(false);
  const imageMaxW = ref(800);

  function cycleContourVisibilityMode() {
    contourVisibilityMode.value = nextModeMap[contourVisibilityMode.value];
  }

  const imageContainer = ref<HTMLDivElement | null>(null);

  {
    const handleResize = () => {
      updateImageMaxW();
    };

    function updateImageMaxW() {
      if (imageContainer.value) {
        const { width } = imageContainer.value.getBoundingClientRect();
        imageMaxW.value = Math.min(width - 20, 800); // 20px for padding
      }
    }
    watch( () => imageContainer.value, (newValue) => { if (newValue) { updateImageMaxW(); } });
    onMounted(() => { window.addEventListener('resize', handleResize); })
    onUnmounted(() => { window.removeEventListener('resize', handleResize); });
  }

  watch(
    () => dataStore.activeDataLabel,
    (newLabel) => {
      nextTick(() => {
        if (newLabel) {
          activeLabel.value = newLabel.items[0]?.id || "";
        }
        unsavedChanges.value = false;
      });
    },
    { immediate: true }
  );
  // deep watch for unsaved changes
  watch(
    () => dataStore.activeDataLabel,
    () => {
      if (!dataStore.activeDataLabel) return;
      unsavedChanges.value = true;
      // console.log("activeLabel altered", dataStore.activeDataLabel);
    },
    { immediate: true, deep: true }
  );

  const predefinedColorsScheme = [
    '#FF5733', '#33FF57', '#3357FF', '#F1C40F', '#8E44AD',
    '#E74C3C', '#3498DB', '#2ECC71', '#9B59B6', '#34495E',
  ];

  function cloneContours(contours: [number, number][][]): [number, number][][] {
    return contours.map(contour => contour.map(point => [...point] as [number, number]));
  }

  function focusOnLabelItem(id: string) {
    const labelItem = document.getElementById('label-item-' + id) as HTMLDivElement;
    if (labelItem) {
      labelItem.scrollIntoView({ behavior: 'smooth', block: 'center' });
      const textInput = labelItem.querySelector('input[type="text"]') as HTMLInputElement;
      if (textInput) {
        textInput.focus();
      }
    }
  }

  function newLabelItem() {
    const id = Date.now().toString() + Math.random().toString(36).substring(2);
    dataStore.activeDataLabel?.items.push({
      id: id,
      lowConfidence: false,
      description: '',
      color: dataStore.activeDataLabel?.items.length < predefinedColorsScheme.length
        ? predefinedColorsScheme[dataStore.activeDataLabel?.items.length]
        : '#' + Math.floor(Math.random() * 16777215).toString(16),
      contours: [],
      autoGenerated: null,
      preRefineContours: null,
    } as LabelItem);
    activeLabel.value = id;
    // focus on the new label item text input
    nextTick(() => {
      focusOnLabelItem(id);
    });
  }

  async function handleContourCommitted(payload: { label: LabelItem; labels: LabelItem[] }) {
    if (
      payload.label.autoGenerated === false ||
      !userStore.settings.enableAIHelpers ||
      !userStore.settings.aiFeatureSet.regionDescriptionOnDraw
    ) {
      return;
    }

    const fileName = dataStore.activeDataItem?.fileName;
    const activeDataLabel = dataStore.activeDataLabel;
    if (!fileName || !activeDataLabel) {
      return;
    }

    const imageId = fileName.replace(/\.[^/.]+$/, '');
    const context = JSON.parse(JSON.stringify({
      ...activeDataLabel,
      items: payload.labels,
    })) as DataLabel;
    context.items = context.items.filter(item => item.id !== payload.label.id);

    try {
      const description = await new AIService().regionDescription(
        imageId,
        payload.label.contours,
        context
      );

      const targetLabel = dataStore.activeDataLabel?.items.find(item => item.id === payload.label.id);
      if (!targetLabel) {
        return;
      }

      targetLabel.description = description;
      targetLabel.autoGenerated = true;
    }
    catch (error) {
      console.error('Error fetching auto-complete:', error);
    }
  }

  async function handleContourDbclick(payload: { label: LabelItem; labels: LabelItem[] }) {
    if (
      !userStore.settings.enableAIHelpers ||
      !userStore.settings.aiFeatureSet.regionRefineOnDoubleClick
    ) {
      return;
    }

    const fileName = dataStore.activeDataItem?.fileName;
    if (!fileName || payload.label.contours.length === 0) {
      return;
    }

    const imageId = fileName.replace(/\.[^/.]+$/, '');

    try {
      const contours = await new AIService().regionRefine(imageId, payload.label.contours);
      const targetLabel = dataStore.activeDataLabel?.items.find(item => item.id === payload.label.id);
      if (!targetLabel) {
        return;
      }
      targetLabel.preRefineContours = cloneContours(payload.label.contours);
      targetLabel.contours = contours.map(contour => resampleContour(contour));
    }
    catch (error) {
      console.error('Error refining contours:', error);
    }
  }

  function restoreContourBackup() {
    if (!activeLabel.value) {
      return;
    }

    const targetLabel = dataStore.activeDataLabel?.items.find(item => item.id === activeLabel.value);
    if (!targetLabel) {
      return;
    }

    if (!targetLabel.preRefineContours) {
      return;
    }

    targetLabel.contours = cloneContours(targetLabel.preRefineContours);
    targetLabel.preRefineContours = null;
  }

  async function saveAndNext() {
    if (unsavedChanges.value) {
      await save();
    }
    await dataStore.loadNextDataItem();
  }

  async function save() {
    console.log("Saving label...");
    if (dataStore.activeDataLabel == null){
      return;
    }
    else{
      console.log("Saving label");
    }
    try {
      loading.value = true;
      await dataStore.saveCurrentLabel();
      unsavedChanges.value = false;
      await dataStore.refreshActiveDataItem();
    }
    catch (error) {
      console.error("Error saving label:", error);
      alert("Error saving label: " + error);
    }
    finally {
      loading.value = false;
    }
  }

  async function skipAndNext (){
    if (dataStore.activeDataLabel == null){
      return;
    }
    // get reason from user
    const reason = prompt("Please enter a reason for skipping this item:", "No reason");
    if (reason == null || reason.trim() === "") {
      return;
    }
    await dataStore.skipActiveData(reason);
    await dataStore.refreshActiveDataItem();
    unsavedChanges.value = false;
    try { loading.value = true; dataStore.loadNextDataItem(); }
    catch (error) { throw error; }
    finally { loading.value = false; }
  }

  async function unSkip (){
    if (dataStore.activeDataLabel == null){
      return;
    }
    await dataStore.unskipActiveData();
    await dataStore.refreshActiveDataItem();
    unsavedChanges.value = false;
  }


  {
    const saveHandler = async (event: KeyboardEvent) => {
      if ((event.ctrlKey || event.metaKey || event.altKey) && event.key === 's') {
        event.preventDefault(); await save();
      }
    };
    const saveAndNextHandler = async (event: KeyboardEvent) => {
      if (event.altKey && event.key === 'n') {
        event.preventDefault(); await saveAndNext();
      }
    };
    const skipHandler = async (event: KeyboardEvent) => {
      if (event.altKey && event.key === 'q') {
        event.preventDefault(); await skipAndNext();
      }
    };
    const tabHandler = async (event: KeyboardEvent) => {
      // Tab to create new label item if no label items exist
      // If label item is active and it's input is not selected, select the input.
      if (event.key === 'Tab') {
        if (dataStore.activeDataLabel?.items.length === 0) {
          event.preventDefault();
          newLabelItem();
          return;
        }

        const isFocusedOnActiveLabelInput = (() => {
          const activeElement = document.activeElement as HTMLElement;
          if (activeElement.tagName.toLowerCase() === 'input') {
            const parent = activeElement.closest('#label-item-' + activeLabel.value);
            if (parent) { return true; }
          }
          return false;
        })();

        if (!isFocusedOnActiveLabelInput) {
          // focus on the active label item input
          console.log('Focusing on active label item input:', activeLabel.value);
          event.preventDefault();
          focusOnLabelItem(activeLabel.value);
          return;
        }

      }
    };
    onMounted(() => {
      window.addEventListener('keydown', saveHandler);
      window.addEventListener('keydown', saveAndNextHandler);
      window.addEventListener('keydown', skipHandler);
      window.addEventListener('keydown', tabHandler);
    });
    onUnmounted(() => {
      window.removeEventListener('keydown', saveHandler);
      window.removeEventListener('keydown', saveAndNextHandler);
      window.removeEventListener('keydown', skipHandler);
      window.removeEventListener('keydown', tabHandler);
    });
  }

</script>

<template>
  <div :class="'flex flex-col gap-4 p-4 bg-white shadow-md rounded-lg' + (loading ? ' opacity-50 pointer-events-none' : '')" v-if="!uiStateStore.labelPanelLoading">

    <div class="flex justify-center items-center p-4 w-full rounded-lg bg-gray-100" ref="imageContainer">
      <div class="relative" v-if="dataStore.activeDataItem && dataStore.activeDataLabel">
        <ImageLabelerContourToggle
          :mode="contourVisibilityMode"
          @cycle="cycleContourVisibilityMode"
        />
        <ImageLabeler
          :imageSrc="dataStore.activeDataItem.imageUrl"
          :max-height="600"
          :max-width="imageMaxW"
          v-model:labels="dataStore.activeDataLabel.items"
          v-model:crop="dataStore.activeDataLabel.crop"
          v-model:activeLabel="activeLabel"
          :contourVisibilityMode="contourVisibilityMode"
          @contour-committed="handleContourCommitted"
          @contour-dbclick="handleContourDbclick"
          @restore-contour-backup="restoreContourBackup"
          >
        </ImageLabeler>
      </div>
      <p v-else class="text-gray-500 text-lg">
        Select an image to start labeling
      </p>
    </div>

    <DescInput
      v-if="dataStore.activeDataItem && dataStore.activeDataLabel"
      v-model="dataStore.activeDataLabel.overallDescription"
      @enter="if (dataStore.activeDataLabel!.items.length > 0) {
        const id = dataStore.activeDataLabel!.items[0]!.id;
        focusOnLabelItem(id)
      }
      else {
        newLabelItem()
      }"
    ></DescInput>

    <div v-if="dataStore.activeDataItem && dataStore.activeDataLabel" class="flex flex-col gap-3">
      <template
        v-for="(label, index) in dataStore.activeDataLabel.items" :key="label.id"
      >
        <LabelItemInput
          v-model="dataStore.activeDataLabel.items[index]!"
          :active-contour-id="activeLabel"
          @delete="(id: string) => {
            const itemIndex = dataStore.activeDataLabel!.items.findIndex(item => item.id === id);
            if (itemIndex !== -1) {
              dataStore.activeDataLabel!.items.splice(itemIndex, 1);
            }
            // focus on the next item if exists, otherwise focus on the previous item
            if (dataStore.activeDataLabel!.items.length > 0) {
              const nextIndex = itemIndex < dataStore.activeDataLabel!.items.length ? itemIndex : itemIndex - 1;
              activeLabel = dataStore.activeDataLabel!.items[nextIndex]!.id;
              focusOnLabelItem(activeLabel);
            }
          }"
          @select="(id) => activeLabel = id"
          @select-previous="() => {
            if (index - 1 >= 0) {
              activeLabel = dataStore.activeDataLabel!.items[index - 1]!.id;
              focusOnLabelItem(activeLabel);
            }
          }"
          @select-next="() => {
            if (index + 1 < dataStore.activeDataLabel!.items.length) {
              activeLabel = dataStore.activeDataLabel!.items[index + 1]!.id;
              focusOnLabelItem(activeLabel);
            }
            else {
              newLabelItem();
            }
          }"
          :id="'label-item-' + label.id"
        />
      </template>
    </div>

    <div class="flex justify-center" v-if="dataStore.activeDataItem && dataStore.activeDataLabel">
      <button
        @click="newLabelItem"
        class="text-gray-700 bg-white hover:bg-gray-100 font-bold rounded-lg text-lg py-2 flex justify-center items-center shadow-md w-full"
      >
        +
      </button>
    </div>

    <!-- Save button -->
    <div class="flex justify-center w-full gap-2"
    >
      <button
        v-if="dataStore.activeDataLabel && dataStore.activeDataItem?.status != FileLabelStatus.SKIPPED"
        @click="skipAndNext"
       class="text-white bg-yellow-600 hover:bg-yellow-700 font-bold rounded-xl text-lg py-2 flex justify-center items-center shadow-md max-w-1/4 w-sm">
        Skip & Next
      </button>
      <button
        v-if="dataStore.activeDataLabel && dataStore.activeDataItem?.status == FileLabelStatus.SKIPPED"
        @click="unSkip"
       class="text-white bg-yellow-600 hover:bg-yellow-700 font-bold rounded-xl text-lg py-2 flex justify-center items-center shadow-md max-w-1/4 w-sm">
        Un-Skip
      </button>

      <button
        v-if="unsavedChanges"
        @click="save"
        class="text-white bg-blue-600 hover:bg-blue-700 font-bold rounded-xl text-lg py-2 flex justify-center items-center shadow-md max-w-1/2 w-lg"
      >
        Save
      </button>
      <button
        @click="saveAndNext"
        class="text-white bg-blue-600 hover:bg-blue-700 font-bold rounded-xl text-lg py-2 flex justify-center items-center shadow-md max-w-1/2 w-lg"
      >
        {{ unsavedChanges ? 'Save & Next' : 'Next' }}
      </button>
    </div>

  </div>
  <div v-else class="flex justify-center items-center p-8 w-full rounded-lg bg-gray-100">
    <div class="text-gray-500 text-lg animate-pulse">
      Loading...
    </div>
  </div>

</template>
