<script setup lang="ts">
import type { LabelItem } from '@/api'
import { ref } from 'vue'

const model = defineModel<LabelItem>({ required: true })
const props = defineProps<{
  activeContourId: string
  transcriptEnabled: boolean
  transcriptBusy?: boolean
  transcriptRecording?: boolean
}>()

const inputRef = ref<HTMLInputElement | null>(null)

const emit = defineEmits<{
  (e: 'delete', id: string): void
  (e: 'select', id: string): void
  (e: 'select-next', ): void
  (e: 'select-previous', ): void
  (e: 'enter', ): void
  (e: 'transcribe', id: string): void
}>()

function toggleLowConfidence() {
  model.value.lowConfidence = !model.value.lowConfidence
}

function randomColor() {
  const letters = '0123456789ABCDEF'
  let color = '#'
  for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)]
  }
  return color
}

function clearContours() {
  model.value.contours = []
  model.value.preRefineContours = null
}

function deleteLabel() {
  emit('delete', model.value.id)
}

function focusInput() {
  inputRef.value?.focus()
}

defineExpose({
  focusInput,
})

const actionBtnBaseClass = 'text-white rounded-xl shadow text-sm inline-flex items-center justify-center px-1.5 py-1 min-w-8 min-h-8 transition-colors'
const actionBtnDisabledClass = 'disabled:opacity-60 disabled:cursor-not-allowed'
</script>

<template>
  <div
    :class="
      'flex items-center gap-3 text-gray-700 px-4 py-2 rounded-xl shadow-sm' +
      (model.id === activeContourId ? ' bg-cyan-50' : ' bg-white')"
    @click="$emit('select', model.id)"
  >

    <div class="flex gap-1">
      <div class="flex flex-col items-center gap-1 self-stretch justify-center w-2" aria-hidden="true">
        <span
          v-if="model.autoGenerated === false"
          class="h-1.5 w-1.5 rounded-full bg-amber-400/55"
          title="Description was manually edited"
        ></span>
        <span
          v-if="model.preRefineContours"
          class="h-1.5 w-1.5 rounded-full bg-cyan-500/45"
          title="Contours were refined"
        ></span>
      </div>

      <!-- ⚠️ Low confidence toggle -->
      <button @click="toggleLowConfidence" title="Toggle low confidence" class="text-xl w-5 cursor-pointer" tabindex="-1">
        <template v-if="model.lowConfidence">❓</template>
        <template v-else>✔</template>
      </button>
    </div>

    <!-- 🎨 Color swatch -->
    <div
      :style="{ backgroundColor: model.color }"
      class="w-6 h-6 rounded border border-black cursor-pointer"
      tabindex="-1"
      @click="model.color = randomColor()"
    ></div>

    <!-- 📝 Description -->
    <input
      ref="inputRef"
      v-model="model.description"
      type="text"
      class="grow bg-transparent border-b border-gray-300 focus:outline-none focus:border-blue-600 text-md"
      placeholder="Enter description"
      @input="model.autoGenerated = false"
      @focus="$emit('select', model.id)"
      @keydown="(e) => {
        if (e.key === 'Tab') {
          e.preventDefault()
          if (!e.shiftKey) {
            $emit('select-next')
          } else {
            $emit('select-previous')
          }
        }
        if (e.key === 'Enter') {
          e.preventDefault()
          $emit('enter')
        }
      }"
    />

    <button
      v-if="props.transcriptEnabled"
      @click.stop="$emit('transcribe', model.id)"
      :disabled="props.transcriptBusy"
      :title="props.transcriptBusy ? 'Transcribing audio' : props.transcriptRecording ? 'Stop recording and transcribe' : 'Start recording audio for this label'"
      :class="[
        actionBtnBaseClass,
        actionBtnDisabledClass,
        props.transcriptRecording ? 'bg-red-600 hover:bg-red-700' : 'bg-emerald-600 hover:bg-emerald-700',
        props.transcriptBusy ? 'disabled:bg-emerald-300' : ''
      ]"
      tabindex="-1"
    >
      <span v-if="props.transcriptBusy" class="text-sm">...</span>
      <svg
        v-else-if="props.transcriptRecording"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
        class="h-3.5 w-3.5"
        aria-hidden="true"
      >
        <rect x="6" y="6" width="12" height="12" rx="2" />
      </svg>
      <svg
        v-else
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        class="h-4 w-4"
        aria-hidden="true"
      >
        <path d="M12 3a3 3 0 0 1 3 3v6a3 3 0 0 1-6 0V6a3 3 0 0 1 3-3Z" />
        <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
        <path d="M12 19v3" />
        <path d="M8 22h8" />
      </svg>
    </button>

    <!-- 🧹 Clear contours -->
    <button
      @click="clearContours"
      title="Clear contours"
      :class="[actionBtnBaseClass, 'bg-blue-600 hover:bg-blue-700']"
      tabindex="-1"
    >
      🧹
    </button>

    <!-- 🗑️ Delete label -->
    <button
      @click="deleteLabel"
      title="Delete label"
      :class="[actionBtnBaseClass, 'bg-red-500 hover:bg-red-600']"
      tabindex="-1"
    >
      🗑️
    </button>
  </div>
</template>
