<script setup lang="ts">
import type { LabelItem } from '@/api'

const model = defineModel<LabelItem>({ required: true })
defineProps<{
  activeContourId: string
}>()

const emit = defineEmits<{
  (e: 'delete', id: string): void
  (e: 'select', id: string): void
  (e: 'select-next', ): void
  (e: 'select-previous', ): void
}>()

function toggleLowConfidence() {
  model.value.lowConfidence = !model.value.lowConfidence
}

function randomColor() {
  const letters = '0123456789ABCDEF'
  let color = '#'
  for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)]
  }
  return color
}

function clearContours() {
  model.value.contours = []
}

function deleteLabel() {
  emit('delete', model.value.id)
}
</script>

<template>
  <div
    :class="
      'flex items-center gap-4 text-gray-700 px-4 py-2 rounded-xl shadow-sm' +
      (model.id === activeContourId ? ' bg-cyan-50' : ' bg-white')"
    @click="$emit('select', model.id)"
  >

    <div class="flex gap-1">
      <div class="flex flex-col items-center gap-1 self-stretch justify-center w-2" aria-hidden="true">
        <span
          v-if="model.autoGenerated === true"
          class="h-1.5 w-1.5 rounded-full bg-amber-400/55"
          title="Description is AI generated"
        ></span>
        <span
          v-if="model.contour_refined === true"
          class="h-1.5 w-1.5 rounded-full bg-cyan-500/45"
          title="Contours were AI refined"
        ></span>
      </div>

      <!-- ⚠️ Low confidence toggle -->
      <button @click="toggleLowConfidence" title="Toggle low confidence" class="text-xl w-5 cursor-pointer" tabindex="-1">
        <template v-if="model.lowConfidence">❓</template>
        <template v-else>✔</template>
      </button>
    </div>

    <!-- 🎨 Color swatch -->
    <div
      :style="{ backgroundColor: model.color }"
      class="w-6 h-6 rounded border border-black cursor-pointer"
      tabindex="-1"
      @click="model.color = randomColor()"
    ></div>

    <!-- 📝 Description -->
    <input
      v-model="model.description"
      type="text"
      class="grow bg-transparent border-b border-gray-300 focus:outline-none focus:border-blue-600 text-md"
      placeholder="Enter description"
      @input="model.autoGenerated = false"
      @focus="$emit('select', model.id)"
      @keydown="(e) => {
        if (e.key === 'Enter' || e.key === 'Tab') {
          e.preventDefault()
          if (!e.shiftKey) {
            $emit('select-next')
          } else {
            $emit('select-previous')
          }
        }
      }"
    />

    <!-- 🧹 Clear contours -->
    <button @click="clearContours" title="Clear contours" class="bg-blue-600 hover:bg-blue-700 text-white px-2 py-1 rounded-xl shadow text-sm" tabindex="-1">
      🧹
    </button>

    <!-- 🗑️ Delete label -->
    <button @click="deleteLabel" title="Delete label" class="bg-red-500 hover:bg-red-600 text-white px-2 py-1 rounded-xl shadow text-sm" tabindex="-1">
      🗑️
    </button>
  </div>
</template>
