import Connector from '@/lfss';
import type { Config } from '@/lfss';
import { useUserStore } from '@/stores/user'

export interface UserInfo {
  username: string,
  isAdmin: boolean
}

export enum FileLabelStatus {
  DONE = "done",
  LABELED = "labeled",
  SKIPPED = "skipped",
  LOCKED = "locked",
  UNLABELED = "unlabeled",
}
export interface DataItem {
  imageUrl: string;     // full image url
  thumbUrl: string;     // full thumbnail url
  fileName: string;     // file name in labeling fs
  status: FileLabelStatus;
}

export interface DataInfo {
  fileName: string;
  path: string;
  source: string;
  height: number;
  width: number;
  id: number;
}

export interface LockStatus {
  lockedBy: string;
  lockTime: string;
  lockExpire: string;
}

export interface DataLabel {
  image_id: number;
  annotators: string[];
  overallDescription: string;
  items: LabelItem[];
  crop: [number, number, number, number] | null; // [x, y, width, height] in normalized coordinates [0,1]
}

export interface LabelItem {
  id: string;
  lowConfidence: boolean;
  description: string;
  color: string;                    // hex color, e.g. "#FF0000"
  contours: [number, number][][];   // x,y in normalized coordinates [0,1]
  autoGenerated?: boolean | null;   // Is it automatically generated by VLM
}

// A wrapper class for lfss to adapt to the application
export class BackendCalls {
  connector: Connector;
  imageDir: string;
  metaDir: string;

  constructor() {
    this.connector = new Connector();
    this.imageDir = '';
    this.metaDir = '';
  }

  configureLFSS(config: Config): BackendCalls {
    console.log("Configuring LFSS connector", config)
    this.connector.config = config;
    return this
  }

  configurePath({ imageDir, metaDir, }: {
    imageDir?: string;
    metaDir?: string;
  }): BackendCalls {
    const fmtPath = (path: string) => {
      if (path.startsWith("/")) { path = path.slice(1); }
      if (path.endsWith("/")) { return path; }
      else { return path + "/"; }
    }
    if (imageDir) this.imageDir = fmtPath(imageDir);
    if (metaDir) this.metaDir = fmtPath(metaDir);
    return this
  }

  async auth(): Promise<UserInfo | null> {
    try {
      const response = await this.connector.whoami();
      return {
        username: response.username,
        isAdmin: response.is_admin
      }
    }
    catch (error) {
      console.error('Error verifying user:', error);
      return null;
    }
  }

  async version(): Promise<string> {
    return await this.connector.version();
  }

  async countData(): Promise<number> {
    return await this.connector.countFiles(this.imageDir, { flat: true });
  }

  _getDataMetaDir(fileName: string): string {
    const fnameRoot = fileName.split(".").slice(0, -1).join(".");
    const fmetaDir = this.metaDir + fnameRoot + "/";
    return fmetaDir;
  }

  // avoid caching
  _mangling(path: string): string {
    const timestamp = new Date().getTime();
    if (path.includes("?")) {
      return path + "&t=" + timestamp;
    }
    else {
      return path + "?t=" + timestamp;
    }
  }

  async isInfoAvailable(fileName: string): Promise<boolean> {
    const metaDir = this._getDataMetaDir(fileName);
    if (!await this.connector.exists(metaDir + 'info.json')) {
      return false;
    }
    return true;
  }

  async querySkip(fileName: string): Promise<string | null> {
    const metaDir = this._getDataMetaDir(fileName);
    const skipFile = metaDir + "skip.json";
    const skipInfo = await this.connector.getMetadata(skipFile);
    if (skipInfo == null) {
      return null;
    }
    const skipData = await this.connector.getJson(skipFile) as { reason: string };
    return skipData.reason;
  }

  async setSkip(fileName: string, reason: string): Promise<void> {
    const metaDir = this._getDataMetaDir(fileName);
    const skipFile = metaDir + "skip.json";
    const skipInfo = {
      reason: reason,
      skipTime: new Date().toISOString(),
    }
    await this.connector.putJson(skipFile, skipInfo, {
      conflict: "overwrite",
    });
  }

  async unSkip(fileName: string): Promise<void> {
    const metaDir = this._getDataMetaDir(fileName);
    const skipFile = metaDir + "skip.json";
    if (await this.connector.getMetadata(skipFile) != null) {
      await this.connector.delete(skipFile);
    }
  }

  async getLabel(fileName: string): Promise<DataLabel> {
    const metaDir = this._getDataMetaDir(fileName);
    const labelFile = metaDir + "label.json";
    const meta = await this.connector.getMetadata(labelFile);
    if (meta == null) {
      return {
        image_id: 0,
        annotators: [],
        overallDescription: "",
        items: [],
        crop: null, // no crop by default
      }
    }
    const label = await this.connector.getJson(this._mangling(labelFile)) as DataLabel;
    // backward compatibility
    if (label.crop === undefined) { label.crop = null; }
    return label;
  }

  async setLabel(fileName: string, label: DataLabel, annotator: string | null = null): Promise<void> {
    const metaDir = this._getDataMetaDir(fileName);
    const flabelFile = metaDir + "label.json";
    // add the annotator to the label
    if (!label.annotators) {  // backward compatibility
      label.annotators = [];
    }
    if (annotator != null && !label.annotators.includes(annotator)) {
      console.debug("add annotator", annotator);
      label.annotators.push(annotator);
    }

    console.info("setLabel", flabelFile, label);
    await this.connector.putJson(flabelFile, label, {
      conflict: "overwrite",
    });
  }

  async getLabelStatus(fileNames: string[], skipUserLock: string | null = null): Promise<FileLabelStatus[]> {
    const fileStatus: Record<string, FileLabelStatus> = {};
    fileNames.forEach((fileName) => {
      // default to UNLABELED
      fileStatus[fileName] = FileLabelStatus.UNLABELED;
    })

    // labeled
    {
      const labelpath2fname: Record<string, string> = {};
      const labelFiles = fileNames.map((fileName) => {
        const labelf = this._getDataMetaDir(fileName) + "label.json"
        labelpath2fname[labelf] = fileName;
        return labelf;
      });
      if (labelFiles.length) {
        const multres = await this.connector.getMultipleText(labelFiles, { skipContent: true });
        const existLabelFiles = Object.keys(multres).filter((fpath) => multres[fpath] != null);
        existLabelFiles.forEach((fpath) => {
          const fileName = labelpath2fname[fpath]!;
          fileStatus[fileName] = FileLabelStatus.LABELED;
        });
      }
    }
    // skip
    {
      const skippath2fname: Record<string, string> = {};
      const skipFiles = fileNames.map((fileName) => {
        const skipf = this._getDataMetaDir(fileName) + "skip.json"
        skippath2fname[skipf] = fileName;
        return skipf;
      });
      if (skipFiles.length) {
        const multres = await this.connector.getMultipleText(skipFiles, { skipContent: true });
        const existSkipFiles = Object.keys(multres).filter((fpath) => multres[fpath] != null);
        existSkipFiles.forEach((fpath) => {
          const fileName = skippath2fname[fpath]!;
          fileStatus[fileName] = FileLabelStatus.SKIPPED;
        });
      }
    }
    // lock
    {
      const lockpath2fname: Record<string, string> = {};
      const lockFiles = fileNames.map(
        (fileName) => {
          const lockf = this._getDataMetaDir(fileName) + "lock.json"
          lockpath2fname[lockf] = fileName;
          return lockf;
        }
      )
      if (lockFiles.length) {
        const existLockContents = await this.connector.getMultipleText(lockFiles);
        const existLockFiles = Object.keys(existLockContents).filter((fpath) => existLockContents[fpath] != null);
        existLockFiles.forEach((fpath) => {
          const fileName = lockpath2fname[fpath]!;
          const lockInfo = JSON.parse(existLockContents[fpath]!) as LockStatus;
          if (new Date(lockInfo.lockExpire) < new Date()) {
            this.connector.delete(fpath);
            console.debug("Remove expired lock file", fpath);
            return;
          }
          if (skipUserLock != null && lockInfo.lockedBy == skipUserLock) {
            return;
          }
          fileStatus[fileName] = FileLabelStatus.LOCKED;
        });
      }
    }

    return fileNames.map((fileName) => fileStatus[fileName]!)
  }

  async listData(
    offset: number,
    limit: number,
    {
      skipUserLock = null as string | null,
    }
  ): Promise<DataItem[]> {
    const files = await this.connector.listFiles(this.imageDir, {
      offset: offset,
      limit: limit,
      orderBy: "url",
    });

    function wrapUrl(url: string, params: object) {
      const urlObj = new URL(url);
      for (const key in params) {
        urlObj.searchParams.append(key, params[key as keyof typeof params]);
      }
      return urlObj.toString();
    }

    const fnames = files.map((file) => {
      const fname = file.url.slice(this.imageDir.length);
      return fname;
    });

    const fileStatus = await this.getLabelStatus(fnames, skipUserLock);
    const fileItems: DataItem[] = files.map((file, i) => {
      const fileUrl = this.connector.config.endpoint + '/' + file.url;
      return {
        imageUrl: wrapUrl(fileUrl, { token: this.connector.config.token }),
        thumbUrl: wrapUrl(fileUrl, { thumb: "true", token: this.connector.config.token }),
        fileName: fnames[i]!,
        status: fileStatus[i]!,
      };
    });

    return fileItems;
  }

  async getDataInfo(fileName: string): Promise<DataInfo> {
    const ret = await this.connector.getJson(this._getDataMetaDir(fileName) + "info.json");
    const validateDataInfo = (data: DataInfo): boolean => {
      return ['file_name', 'path', 'source', 'height', 'width', 'id'].every(prop => prop in data);
    }
    if (!validateDataInfo(ret as DataInfo)) {
      throw new Error("Invalid data info format for " + fileName);
    }
    function toCamelCase(str: string) {
      return str.replace(/_([a-z])/g, (match, letter) => letter.toUpperCase());
    }
    // make fields camelCase
    const camelCaseRet: { [key: string]: unknown } = {};
    for (const key in ret) {
      camelCaseRet[toCamelCase(key)] = ret[key as keyof typeof ret];
    }
    return camelCaseRet as unknown as DataInfo;
  }

  // maybe not needed...
  async getLockDetail(fitem: DataItem): Promise<LockStatus | null> {
    const lockFile = this._getDataMetaDir(fitem.fileName) + "lock.json";
    const lockInfo = await this.connector.getJson(lockFile) as LockStatus;
    return lockInfo;
  }

  /**
   * Try to lock a file for labeling,
   * if the lock is successfully acquired, return [true, lockInfo by the current user]
   * if the file is already locked by another user, return [false, lockInfo by the other user]
   * This will catch write permission errors internally and will not throw for this
   */
  async tryLock(fitem: DataItem, user: UserInfo | null = null): Promise<[boolean, LockStatus]> {
    const lockFile = this._getDataMetaDir(fitem.fileName) + "lock.json";
    user = user || (await this.auth());

    const EXPIRE_TIME = 10 * 60 * 1000; // 10 min
    const doLock = async () => {
      const lockInfo: LockStatus = {
        lockedBy: user!.username,
        lockTime: new Date().toISOString(),
        lockExpire: new Date(Date.now() + EXPIRE_TIME).toISOString(), // 1 hour
      };
      try {
        await this.connector.putJson(lockFile, lockInfo, {
          conflict: "overwrite",
        });
        console.debug("lock file created at", lockFile);
        console.debug("lock info", lockInfo);
        return lockInfo;
      }
      catch (e) {
        console.error("Failed to create lock file at", lockFile, e);
        return {
          ...lockInfo,
          lockedBy: "",
        }
      }
    }

    // lock file does not exist, create it
    if (await this.connector.getMetadata(lockFile) == null) {
      return [true, await doLock()];
    }

    // already locked, check if the lock is by the same user or is expired
    const lockInfo = await this.connector.getJson(lockFile) as LockStatus;
    if (lockInfo.lockedBy == user!.username || new Date(lockInfo.lockExpire) < new Date()) {
      return [true, await doLock()];
    }
    else {
      // actively locked by another user
      return [false, lockInfo];
    }
  }

  /**
   * Try to unlock a file for labeling,
   * if the file is not locked by the current user, do nothing
   * This will catch write permission errors internally and will not throw for this
   */
  async tryUnlock(fitem: DataItem, user: UserInfo | null = null): Promise<void> {
    const lockFile = this._getDataMetaDir(fitem.fileName) + "lock.json";
    user = user || (await this.auth());
    if (user == null) { return; }    // should be impossible
    let lockInfo: LockStatus;
    try {
      lockInfo = await this.connector.getJson(lockFile) as LockStatus;
    }
    catch (e) {
      console.error("Failed to get lock file at", lockFile, e);
      return;
    }
    if (lockInfo.lockedBy == user.username || new Date(lockInfo.lockExpire) < new Date()) {
      try {
        await this.connector.delete(lockFile);
        console.debug("lock file deleted at", lockFile);
      }
      catch (e) {
        console.error("Failed to delete lock file at", lockFile, e);
      }
    }
  }
}


interface AIGenerateResponse {
  idx: number;
  question: string;
  output: string;
}

export class AIBackendCalls {

  getBaseUrl(): string {
    const userStore = useUserStore()
    const settings = userStore.settings
    if (!settings.enableAIAutoGen) {
      throw new Error('AI auto generation disabled. Switched to manual input.')
    }
    if (!settings.aiBackendUrl) {
      userStore.disableAIAutoGen()
      throw new Error('AI backend URL not configured. Switched to manual input.')
    }
    return settings.aiBackendUrl.replace(/\/$/, '')
  }

  async fetch(route: string, payload: any): Promise<AIGenerateResponse> {
    const baseUrl = this.getBaseUrl()
    const finalUrl = `${baseUrl}/${route}`
    const userStore = useUserStore()
    try {
      const res = await fetch(finalUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${userStore.settings.aiBackendToken}`
        },
        body: JSON.stringify(payload),
      })

      if (!res.ok) {
        throw new Error(`HTTP ${res.status}`)
      }

      const data = await res.json();
      return data;
    } catch (err) {
      console.error('AI backend call failed:', err)
      userStore.disableAIAutoGen()
      throw err
    }
  }

  public async overallDescription(idx: string): Promise<string> {
    const response = await this.fetch('overall-description', { idx });
    return response.output || "";
  }

  public async regionDescription(idx: string, contours: [number, number][][]): Promise<string> {
    const response = await this.fetch('region-description', { idx, contours });
    return response.output || "";
  }

}
